### ISSUE TITLE
Remove bloom compactor component

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#13957]
### Background 

Some time ago, a two new components for building bloom filters were introduced: the bloom planner and the bloom builder.

These new components fulfil the same functionality as the the compactor, however, they come with certain advantages:

- The consistent hash ring for the compactors is removed. The ring is hard to operate and configure and causes problems with the ownership of fingerprint ranges when instances are added and removed regularly (e.g. due to OOMing)
- The planner/builder approach can distribute load better, because builders get new tasks from the queue whenever their previous task is completed. This reduces idle time of instances.
- Only the planner is "stateful", since it keeps the queue. Builders are stateless and can be scaled horizontally depending on the needs, without changing the fingerprint ranges of the tasks (which was the case when running compactors). This can enable huge cost savings, because planners can be run on spot instances.

#### List of PRs

- https://github.com/grafana/loki/pull/12989
- https://github.com/grafana/loki/pull/12994
- https://github.com/grafana/loki/pull/13005
- https://github.com/grafana/loki/pull/13015
- https://github.com/grafana/loki/pull/13046
- https://github.com/grafana/loki/pull/13064
- https://github.com/grafana/loki/pull/13074
- https://github.com/grafana/loki/pull/13078
- https://github.com/grafana/loki/pull/13133
- https://github.com/grafana/loki/pull/13139
- https://github.com/grafana/loki/pull/13153
- https://github.com/grafana/loki/pull/13306
- https://github.com/grafana/loki/pull/13361
- https://github.com/grafana/loki/pull/13363
- https://github.com/grafana/loki/pull/13484
- https://github.com/grafana/loki/pull/13506
- https://github.com/grafana/loki/pull/13677

### Change request

> :warning: **Note**
> Bloom filters are an experimental feature and therefore subject to rapid changes.

Because of these new components, the bloom compactor should not be considered any more and existing deployments should be migrated as soon as possible.

#### TODOs

- [x] Update documentation to reference bloom planner and builders
- [x] Integrate bloom building into SSD deployment
- [x] Remove all bloom compactor related code
- [x] Update Helm chart (distributed) to use the new components

**Comment by LukoJy3D** [comment]
Love this initiative!

**Comment by chaudum** [comment]
This can be considered as complete.
