### ISSUE TITLE
[Epic] Refactor docs content to better fit the new architecture

### ISSUE THREAD

**Issue by JStickler** [grafana/loki#8721]
The doc squads for Loki, Tempo, and Mimir have been meeting regularly for two months to create a common information architecture for the three projects.  This will make it easier for users to find the information that they’re looking for across the stack.
Phase One  (#8710) of the information architecture restructuring was just moving entire files.  But many files contain content that should fall under two different headings.
Phase Two (this Epic) involves refactoring each file to see if any content in the file should be moved to a different section under the new information architecture.  This may involve splitting files into two or more separate files, and moving them to a more appropriate section.

References
- (Internal) https://github.com/grafana/technical-documentation/issues/538
- Mimir Epic https://github.com/grafana/mimir/issues/4274 

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/loki/issues/9228
- [ ] https://github.com/grafana/loki/issues/9229
- [ ] https://github.com/grafana/loki/issues/9230
- [ ] https://github.com/grafana/loki/issues/9231
- [ ] https://github.com/grafana/loki/issues/9232
- [ ] https://github.com/grafana/loki/issues/9233
- [ ] https://github.com/grafana/loki/issues/9234
- [ ] https://github.com/grafana/loki/issues/9235
- [ ] https://github.com/grafana/loki/issues/9238
- [ ] https://github.com/grafana/loki/issues/9237
- [ ] https://github.com/grafana/loki/issues/9227
```

**Comment by JStickler** [comment]
Closing this epic as completed. The Loki documentation has been substantially restructured since this epic was created, with new top-level sections aligned with the common information architecture across Loki, Tempo, and Mimir.
